apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: rust-blog
type: Opaque
data:
  # your-super-secret-jwt-key-change-this-in-production
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtdGhpcy1pbi1wcm9kdWN0aW9u