apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-blog-app
  namespace: rust-blog
  labels:
    app: rust-blog-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rust-blog-app
  template:
    metadata:
      labels:
        app: rust-blog-app
    spec:
      containers:
      - name: rust-blog
        image: rust-blog:latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: "postgres://postgres:password@postgres-service:5432/rust_blog"
        - name: RUST_LOG
          value: "info"
        - name: PORT
          value: "3000"
        envFrom:
        - secretRef:
            name: app-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: static-files
          mountPath: /app/static
      volumes:
      - name: static-files
        emptyDir: {}